# Run Scripts with `bx <script-name>`
version = "0.3.2"

[scripts]
    doty.cmd         = "cargo run -- %%"
    doty.description = "Run the doty CLI with any flag"

    # run specific cli commands 
    rhelp.cmd         = "cargo run -- --help"
    rhelp.description = "Show the help for the doty CLI"
    rv.cmd            = "cargo run -- --version"
    rv.description    = "Show the version of the doty CLI"

    pg.cmd                = "cargo run -- link -c playground/doty.kdl %%"
    pg.description        = "Run the doty CLI with the playground config"
    pg-dry.cmd            = "cargo run -- link --dry-run -c playground/doty.kdl"
    pg-dry.description    = "Dry run the doty CLI with the playground config"
    pg-i.cmd              = "cargo run -- link -c playground/doty.kdl"
    pg-i.description      = "Run the doty CLI with the playground config"
    pg-detect.cmd         = "cargo run -- detect -c playground/doty.kdl %%"
    pg-detect.description = "Detect drift in the playground config"

    # cargo shortcuts 
    test = "cargo test %%"
